package com.example.Royal_Blueberry.controller;

import com.example.Royal_Blueberry.config.OpenApiConfig;
import com.example.Royal_Blueberry.dto.auth.*;
import com.example.Royal_Blueberry.security.CustomUserDetails;
import com.example.Royal_Blueberry.service.AuthService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
@Tag(name = "Authentication", description = "Authentication endpoints")
public class AuthController {

    private final AuthService authService;

    @Operation(
            summary = "Get Google login URL",
            description = """
                    Returns the Google login URL generated by the backend.
                    The response includes the `state`, configured `redirectUri`, and requested `scope`.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Google login URL generated"),
            @ApiResponse(responseCode = "500", description = "Google login is not configured")
    })
    @GetMapping("/google/url")
    public ResponseEntity<GoogleLoginUrlResponse> getGoogleLoginUrl() {
        return ResponseEntity.ok(authService.getGoogleLoginUrl());
    }


    @Operation(
            summary = "Login with email and password",
            description = """
                    Authenticates a user with email and password.
                    Returns an access token, refresh token, and user information.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Login successful"),
            @ApiResponse(responseCode = "401", description = "Invalid credentials")
    })
    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request) {
        AuthResponse response = this.authService.login(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Register a new user",
            description = """
                    Creates a new local user account.
                    The default role is USER and JWT tokens are returned on success.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Registration successful"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "409", description = "Username or email already exists")
    })
    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest request) {
        AuthResponse response = authService.register(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Login with Google",
            description = """
                    Completes Google login using the authorization `code` and `state`
                    returned by the Google callback.
                    If the user does not exist, a new Google account is created automatically.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Google login successful"),
            @ApiResponse(responseCode = "401", description = "Invalid Google authorization code or state"),
            @ApiResponse(responseCode = "409",
                    description = "Email already registered with local account")
    })
    @PostMapping("/google")
    public ResponseEntity<AuthResponse> loginWithGoogle(
            @Valid @RequestBody GoogleLoginRequest request) {
        AuthResponse response = authService.loginWithGoogle(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Refresh access token",
            description = """
                    Uses a valid refresh token to issue a new access token.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Token refreshed successfully"),
            @ApiResponse(responseCode = "401", description = "Invalid or expired refresh token")
    })
    @PostMapping("/refresh-token")
    public ResponseEntity<AuthResponse> refreshToken(
            @Valid @RequestBody RefreshTokenRequest request) {
        AuthResponse response = authService.refreshToken(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Get current authenticated user",
            description = "Returns the profile of the currently authenticated user.",
            security = @SecurityRequirement(name = OpenApiConfig.SECURITY_SCHEME_NAME))
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "User info returned"),
            @ApiResponse(responseCode = "401", description = "Not authenticated")
    })
    @GetMapping("/me")
    public ResponseEntity<UserInfo> getCurrentUser(
            @AuthenticationPrincipal CustomUserDetails userDetails) {
        UserInfo userInfo = authService.getCurrentUser(userDetails.getUser().getId());
        return ResponseEntity.ok(userInfo);
    }
}
